# Generated by Django 4.2.4 on 2023-08-07 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0005_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='uncategories', max_length=255),
        ),
    ]
