# Generated by Django 4.2.4 on 2023-08-11 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0010_remove_post_body_alter_post_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
